### PR TITLE
Remove eloquent-sluggable package and create Slug class + HasSlug trait

### PR DESCRIPTION
**Pull request by MPur**
references to #2  PR
I created Slug class and HasSlug trait to remove eloquent-sluggable package.. 
You're right @SandeeshS this repo doesn't use too many dependencies but I think It can be useful to learn how implement this feature in a laravel way without any package.

What we have here  : 
- Slug class to générate unique slug based on string value
- HasSlug trait to add the feature for Model
- set slug column
- set source attribute to slugify
- set banned/reserved values

### CODE REVIEW

**Comment by SandeeshS** [comment]
@MPur thank you. I'm kinda busy today, i'll have a test with this once i'm free and merge them

**Comment by MPur** [comment]
@SandeeshS i fix this tomorow if you wish but I think "HasSlug" for name is more Laravel way.
I mean for example `Concerns\HasAttributes` and `Concerns\HasTimestamps` trait are in a Laravel core for Model class. 

I used to name my trait in this way : 
- Has-noun
- Verb-able

I rebased the PR. Just need to change structure now. 👍

**Comment by SandeeshS** [comment]
@MPur that makes sense. Keep it to HasSlug :+1:

**Comment by MPur** [comment]
@SandeeshS I create folder called Sluggable.

**Comment by MPur** [comment]
@SandeeshS obviously. My bad sorry. It is good now.

**Pull request merged**
