### PR TITLE
Remove eloquent-sluggable package and create simple HasSlug trait

### PR DESCRIPTION
**Pull request by MPur**
I propose to remove this package and create our trait.

### CODE REVIEW

**Comment by SandeeshS** [comment]
The current package is used to generate unique slugs in case if it's already in use. The PR doesn't do it. Also the slug 'feed' is reserved to prevent route conflict with user feed endpoint. If you can add these functionality then i'll accept it :)

**Comment by MPur** [comment]
I will do this when I come back to home. I also remove the reference on reader.md

**Comment by SandeeshS** [comment]
I feel the package is adequate and does what we want in a clean way. The complete project is already built with only 2 other dependencies apart from this. This is still a very light dependency. I think we should leave it at that. If you feel you can add a cleaner solution without the package then feel free to have me reopen this or create a new PR.

**Comment by MPur** [comment]
Sorry for waiting, I've been a little busy.
@SandeeshS You can check my implementation and feel free to acccept it. I think less dependencies we have, more usefull this package is.

**Pull request closed without merging**
